version: '3'
services:
  web:
    build: .
    command: pm2-docker start ecosystem.config.js
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      EO_SESSION_SECRET: 'test'
      EO_DB_HOST: postgres://uduser@postgres/uddb
      EO_DB_USER: uduser
      EO_DB_PASSWORD: udpass
      EO_DB_DATABASE: uddb
    restart: on-failure
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: uduser
      POSTGRES_PASSWORD: udpass
      POSTGRES_DB: uddb
